export const premierLeague = [
    {
        position: 1,
        team: "Arsenal",
        played: 10,
        won: 8,
        drawn: 1,
        lost: 1,
        points: 25,
        logo: "https://r2.thesportsdb.com/images/media/team/logo/4jwa1i1599314931.png",
    },
    {
        position: 2,
        team: "Manchester City",
        played: 10,
        won: 7,
        drawn: 2,
        lost: 1,
        points: 23,
        logo: "https://r2.thesportsdb.com/images/media/team/logo/4jwa1i1599314931.png",
    },
    {
        position: 3,
        team: "Liverpool",
        played: 10,
        won: 6,
        drawn: 3,
        lost: 1,
        points: 21,
        logo: "https://r2.thesportsdb.com/images/media/team/logo/4jwa1i1599314931.png",
    },
    {
        position: 4,
        team: "Chelsea",
        played: 10,
        won: 5,
        drawn: 4,
        lost: 1,
        points: 19,
        logo: "https://r2.thesportsdb.com/images/media/team/logo/4jwa1i1599314931.png",
    },
    {
        position: 5,
        team: "Manchester United",
        played: 10,
        won: 5,
        drawn: 3,
        lost: 2,
        points: 18,
        logo: "https://r2.thesportsdb.com/images/media/team/logo/4jwa1i1599314931.png",
    },
    {
        position: 6,
        team: "Tottenham Hotspur",
        played: 10,
        won: 4,
        drawn: 4,
        lost: 2,
        points: 16,
        logo: "https://r2.thesportsdb.com/images/media/team/logo/4jwa1i1599314931.png",
    },
]